apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-04-13T16:03:50Z"
  labels:
    app: nginx
  name: nginx-deployment
  namespace: default
  resourceVersion: "18708"
  selfLink: /api/v1/namespaces/default/services/nginx-deployment
  uid: ba2ff0a7-5e05-11e9-b52f-6e7573d30673
spec:
  clusterIP: 10.99.14.79
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
